# Generated by Django 4.2.2 on 2023-06-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_reciperequirement_unit_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='unit',
            field=models.CharField(choices=[('tbsp', 'tbsp'), ('gram', 'Gram'), ('kg', 'KiloGram'), ('mg', 'MiliGram'), ('unit', 'Unit')], max_length=5, null=True),
        ),
    ]
