# Generated by Django 4.2.2 on 2023-07-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_reciperequirement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tbsp', 'tbsp'), ('gram', 'Gram'), ('kg', 'KiloGram'), ('mg', 'MiliGram'), ('unit', 'Unit')], max_length=5, null=True),
        ),
    ]
